# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rSA7zl_iZc5lpt2wLA7lUJy0MxhSnLQQ
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

data = pd.read_csv('/content/diabetes.csv')
data.head()

data.shape

data.isnull().sum()

X = data.drop(['Outcome'],axis=1)
y = data['Outcome']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

svc = svm.SVC()
svc.fit(X_train,y_train)

X_train_prediction = svc.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, y_train)

training_data_accuracy

X_test_prediction = svc.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, y_test)
test_data_accuracy

import pickle

filename = "diabetes.sav"
pickle.dump(svc, open(filename, 'wb'))

data.columns

